## Exploratory Data Analysis (EDA) on Telecommunications Data

### Data Extraction

In [1]:
import os
os.chdir('..')
from src.dbconnection import get_dataFrame_from_database

#### Extract telecommunications data from the XDR_data table

In [2]:
xdr_data = get_dataFrame_from_database()

In [3]:
xdr_data.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

#### Number of rows and columns

In [4]:
print("rows=", xdr_data.shape[0], "columns=", xdr_data.shape[1])

rows= 150001 columns= 55

### Find any missing values

In [5]:
import pandas as pd
def find_missing_values(df):
    """
    Finds missing values and returns a summary.

    Args:
        df: The DataFrame to check for missing values.

    Returns:
        A summary of missing values, including the number of missing values per column.
    """

    missing_data = df.isnull().sum()
    missing_data_summary = pd.DataFrame({'Missing Values': missing_data})
    # missing_data_summary = missing_data_summary[missing_data_summary['Missing Values'] > 0]

    return missing_data_summary
missing_summary = find_missing_values(xdr_data)
missing_summary.head(missing_summary.size)

                                          Missing Values
Bearer Id                                            991
Start                                                  1
Start ms                                               1
End                                                    1
End ms                                                 1
Dur. (ms)                                              1
IMSI                                                 570
MSISDN/Number                                       1066
IMEI                                                 572
Last Location Name                                  1153
Avg RTT DL (ms)                                    27829
Avg RTT UL (ms)                                    27812
Avg Bearer TP DL (kbps)                                1
Avg Bearer TP UL (kbps)                                1
TCP DL Retrans. Vol (Bytes)                        88146
TCP UL Retrans. Vol (Bytes)                        96649
DL TP < 50 Kbps (%)                                  754
50 Kbps < DL TP < 250 Kbps (%)                       754
250 Kbps < DL TP < 1 Mbps (%)                        754
DL TP > 1 Mbps (%)                                   754
UL TP < 10 Kbps (%)                                  792
10 Kbps < UL TP < 50 Kbps (%)                        792
50 Kbps < UL TP < 300 Kbps (%)                       792
UL TP > 300 Kbps (%)                                 792
HTTP DL (Bytes)                                    81474
HTTP UL (Bytes)                                    81810
Activity Duration DL (ms)                              1
Activity Duration UL (ms)                              1
Dur. (ms).1                                            1
Handset Manufacturer                                 572
Handset Type                                         572
Nb of sec with 125000B < Vol DL                    97538
Nb of sec with 1250B < Vol UL < 6250B              92894
Nb of sec with 31250B < Vol DL < 125000B           93586
Nb of sec with 37500B < Vol UL                    130254
Nb of sec with 6250B < Vol DL < 31250B             88317
Nb of sec with 6250B < Vol UL < 37500B            111843
Nb of sec with Vol DL < 6250B                        755
Nb of sec with Vol UL < 1250B                        793
Social Media DL (Bytes)                                0
Social Media UL (Bytes)                                0
Google DL (Bytes)                                      0
Google UL (Bytes)                                      0
Email DL (Bytes)                                       0
Email UL (Bytes)                                       0
Youtube DL (Bytes)                                     0
Youtube UL (Bytes)                                     0
Netflix DL (Bytes)                                     0
Netflix UL (Bytes)                                     0
Gaming DL (Bytes)                                      0
Gaming UL (Bytes)                                      0
Other DL (Bytes)                                       0
Other UL (Bytes)                                       0
Total UL (Bytes)                                       1
Total DL (Bytes)                                       1

In [6]:
# Data cleaning
import pandas as pd

def replace_missing_values(data):
  """
  Replaces missing values in a DataFrame with the mean for numeric columns and the mode for categorical columns.

  Args:
    data (pd.DataFrame): The input DataFrame.

  Returns:
    pd.DataFrame: The DataFrame with missing values replaced.
  """

  # Identify numeric and categorical columns
  numeric_columns = data.select_dtypes(include='number').columns
  categorical_columns = data.select_dtypes(include='object').columns

  # Replace missing values in numeric columns with the mean
  for column in numeric_columns:
    column_mean = data[column].mean()
    data[column] = data[column].fillna(column_mean)

  # Replace missing values in categorical columns with the mode
  for column in categorical_columns:
    column_mode = data[column].mode().iloc[0]
    data[column] = data[column].fillna(column_mode)

  return data

# Example usage:
# Assuming you have a DataFrame named 'df'
df = replace_missing_values(xdr_data)

In [7]:
missing_summary = find_missing_values(xdr_data)
missing_summary.head(missing_summary.size)

                                          Missing Values
Bearer Id                                              0
Start                                                  0
Start ms                                               0
End                                                    0
End ms                                                 0
Dur. (ms)                                              0
IMSI                                                   0
MSISDN/Number                                          0
IMEI                                                   0
Last Location Name                                     0
Avg RTT DL (ms)                                        0
Avg RTT UL (ms)                                        0
Avg Bearer TP DL (kbps)                                0
Avg Bearer TP UL (kbps)                                0
TCP DL Retrans. Vol (Bytes)                            0
TCP UL Retrans. Vol (Bytes)                            0
DL TP < 50 Kbps (%)                                    0
50 Kbps < DL TP < 250 Kbps (%)                         0
250 Kbps < DL TP < 1 Mbps (%)                          0
DL TP > 1 Mbps (%)                                     0
UL TP < 10 Kbps (%)                                    0
10 Kbps < UL TP < 50 Kbps (%)                          0
50 Kbps < UL TP < 300 Kbps (%)                         0
UL TP > 300 Kbps (%)                                   0
HTTP DL (Bytes)                                        0
HTTP UL (Bytes)                                        0
Activity Duration DL (ms)                              0
Activity Duration UL (ms)                              0
Dur. (ms).1                                            0
Handset Manufacturer                                   0
Handset Type                                           0
Nb of sec with 125000B < Vol DL                        0
Nb of sec with 1250B < Vol UL < 6250B                  0
Nb of sec with 31250B < Vol DL < 125000B               0
Nb of sec with 37500B < Vol UL                         0
Nb of sec with 6250B < Vol DL < 31250B                 0
Nb of sec with 6250B < Vol UL < 37500B                 0
Nb of sec with Vol DL < 6250B                          0
Nb of sec with Vol UL < 1250B                          0
Social Media DL (Bytes)                                0
Social Media UL (Bytes)                                0
Google DL (Bytes)                                      0
Google UL (Bytes)                                      0
Email DL (Bytes)                                       0
Email UL (Bytes)                                       0
Youtube DL (Bytes)                                     0
Youtube UL (Bytes)                                     0
Netflix DL (Bytes)                                     0
Netflix UL (Bytes)                                     0
Gaming DL (Bytes)                                      0
Gaming UL (Bytes)                                      0
Other DL (Bytes)                                       0
Other UL (Bytes)                                       0
Total UL (Bytes)                                       0
Total DL (Bytes)                                       0

### Find  outliers

In [8]:
# import pandas as pd

# def find_outliers(data, column_name):
#     """
#     Finds outliers in a given column of a DataFrame using the IQR method.

#     Args:
#         data (pd.DataFrame): The input DataFrame.
#         column_name (str): The name of the column to check for outliers.

#     Returns:
#         pd.Series: A Series containing the outliers.
#     """

#     q1 = data[column_name].quantile(0.25)
#     q3 = data[column_name].quantile(0.75)
#     iqr = q3 - q1
#     lower_bound = q1 - 1.5 * iqr
#     upper_bound = q3 + 1.5 * iqr

#     outliers = data[(data[column_name] < lower_bound) | (data[column_name] > upper_bound)]
#     return outliers

# def remove_outliers_winsorization(data, column_names):
#     """
#     Removes outliers from specified columns of a DataFrame using winsorization.

#     Args:
#         data (pd.DataFrame): The input DataFrame.
#         column_names (list): A list of column names to process.

#     Returns:
#         pd.DataFrame: The DataFrame with outliers removed.
#     """

#     for column_name in column_names:
#         q1 = data[column_name].quantile(0.25)
#         q3 = data[column_name].quantile(0.75)
#         iqr = q3 - q1
#         lower_bound = q1 - 1.5 * iqr
#         upper_bound = q3 + 1.5 * iqr
#         data[column_name] = data[column_name].clip(lower_bound, upper_bound)

#     return data

# # Example usage:
# # Assuming you have a DataFrame named 'df'
# outliers = find_outliers(xdr_data, 'Avg RTT DL (ms)')
# outliers.shape[0]
# # print("Outliers:", outliers)

# # Remove outliers using winsorization
# # df_cleaned = remove_outliers_winsorization(df, ['column_name1', 'column_name2'])

In [9]:
# import seaborn as sns
# import matplotlib.pyplot as plt
# sns.boxplot(data=xdr_data['Avg RTT DL (ms)'], orient='v')
# plt.title('Box Plot')
# plt.xlabel('Values')
# plt.ylabel('Avg RTT DL (ms)')
# plt.show()

In [120]:
# User overview analysis
top_handsets = xdr_data['Handset Type'].value_counts().head(5)
top_manufacturers = xdr_data['Handset Manufacturer'].value_counts().head(3)

In [121]:
print(top_handsets)

Handset Type
Huawei B528S-23A           20324
Apple iPhone 6S (A1688)     9419
Apple iPhone 6 (A1586)      9023
undefined                   8987
Apple iPhone 7 (A1778)      6326
Name: count, dtype: int64

#### Top three handset manufacturers

In [122]:
top_manufacturers.head()

Handset Manufacturer
Apple      60137
Samsung    40839
Huawei     34423
Name: count, dtype: int64

In [117]:
import pandas as pd

# Assuming you have a DataFrame named 'xdr_data'

# Get top 3 manufacturers
top_manufacturers = xdr_data['Handset Manufacturer'].value_counts().head(3)

# Filter the data for top manufacturers
filtered_data = xdr_data[xdr_data['Handset Manufacturer'].isin(top_manufacturers.index)]

# Group by 'Handset Manufacturer' and get the top 5 handsets for each manufacturer
for h_type in top_manufacturers.index:
    top_5_handsets_per_manufacturer = filtered_data[filtered_data['Handset Manufacturer']==h_type].groupby('Handset Manufacturer')['Handset Type'].value_counts().head(5)

    # Print the results
    print(top_5_handsets_per_manufacturer)

Handset Manufacturer  Handset Type
Apple                 Apple iPhone 6S (A1688)    9419
                      Apple iPhone 6 (A1586)     9023
                      Apple iPhone 7 (A1778)     6326
                      Apple iPhone Se (A1723)    5187
                      Apple iPhone 8 (A1905)     4993
Name: count, dtype: int64
Handset Manufacturer  Handset Type
Samsung               Samsung Galaxy S8 (Sm-G950F)    4520
                      Samsung Galaxy A5 Sm-A520F      3724
                      Samsung Galaxy J5 (Sm-J530)     3696
                      Samsung Galaxy J3 (Sm-J330)     3484
                      Samsung Galaxy S7 (Sm-G930X)    3199
Name: count, dtype: int64
Handset Manufacturer  Handset Type
Huawei                Huawei B528S-23A                  19752
                      Huawei E5180                       2079
                      Huawei P20 Lite Huawei Nova 3E     2021
                      Huawei P20                         1480
                      Huawei Y6 2018                      997
Name: count, dtype: int64

In [135]:
def aggregate_xdr_data(df):
    """Aggregates xDR data per user and application.

    Args:
        df (pandas.DataFrame): The cleaned xDR data.

    Returns:
        pandas.DataFrame: The aggregated xDR data.
    """

    # Assuming the column names are as provided in the prompt
    columns = ['IMSI', 'Dur. (ms)', 'Start','End', 'Total DL (Bytes)', 'Total UL (Bytes)']

    df = df[columns]

    # Calculate session duration in seconds
    # df['Session_Duration'] = (df['End'] - df['Start']) / 1000

    # Aggregate data
    aggregated_df = df.groupby('IMSI').agg(
        # Number_of_Sessions=('Session_Duration', 'count'),
        Total_Duration=('Session_Duration', 'sum'),
        Total_Download=('Total DL (Bytes)', sum),
        Total_Upload=('Total UL (Bytes)', sum)
        # Total_Data_Volume=('Download_Data' + 'Upload_Data', 'sum')
    )

    return aggregated_df

In [136]:
aggregate_xdr_data(xdr_data)

/tmp/ipykernel_30643/1688967247.py:20: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  aggregated_df = df.groupby('IMSI').agg(

              Total_Download  Total_Upload
IMSI
2.040471e+14      78697597.0    60456049.0
2.040808e+14     194828056.0    37295915.0
2.082001e+14      31376981.0    53794658.0
2.082001e+14     392918313.0    33583272.0
2.082001e+14     961767023.0    71325004.0
...                      ...           ...
2.082099e+14     688815403.0    33888182.0
2.082099e+14     451173021.0    44692550.0
2.082099e+14     307825104.0    30355487.0
2.082522e+14     800629358.0    45083854.0
2.140743e+14     637123579.0    57382080.0

[107266 rows x 2 columns]